import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, DM_Sans } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { StyledEngineProvider } from "@mui/material";

const geistPoppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "600",
});

const geistDM_Sans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${geistDM_Sans.variable} ${geistPoppins.variable}`}>
      <body>
        <StyledEngineProvider injectFirst>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>{children}</AppRouterCacheProvider>
        </StyledEngineProvider>
      </body>
    </html>
  );
}
